services:
  cbl:
    container_name: cbl_container
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./cbl/.env
    ports:
      - 8081:8001

  mtb:
    container_name: mtb_container
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./mtb/.env
    ports:
      - 8082:8002
